# fly.toml app configuration file generated for activitiespwa-notifications-kkgxta on 2025-10-10T23:44:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'activitiespwa-notifications-kkgxta'
primary_region = 'gru'

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  
  auto_stop_machines = 'false'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.ports]]
    handlers = ["http"]
    port = 80
  
[[http_service.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
